### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by FriedChckn** [PugFreedom/WolfFreedom-Core#11]
This is not needed as we do not have an onine logviewer.
`package me.totalfreedom.totalfreedommod.command;

import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import me.totalfreedom.totalfreedommod.LogViewer.LogsRegistrationMode;
import me.totalfreedom.totalfreedommod.TotalFreedomMod;
import me.totalfreedom.totalfreedommod.admin.Admin;
import me.totalfreedom.totalfreedommod.config.ConfigEntry;
import me.totalfreedom.totalfreedommod.rank.Rank;
import me.totalfreedom.totalfreedommod.util.FLog;
import org.apache.commons.lang3.StringUtils;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.scheduler.BukkitRunnable;

@CommandPermissions(level = Rank.SUPER_ADMIN, source = SourceType.ONLY_IN_GAME)
@CommandParameters(description = "Register your connection with the TFM logviewer.", usage = "/ [off]")
public class Command_logs extends FreedomCommand
{

@Override
public boolean run(final CommandSender sender, final Player playerSender, Command cmd, String commandLabel, String[] args, boolean senderIsConsole)
{
    LogsRegistrationMode mode = LogsRegistrationMode.UPDATE;

    if (args.length == 1)
    {
        mode = ("off".equals(args[0]) ? LogsRegistrationMode.DELETE : LogsRegistrationMode.UPDATE);
    }

    plugin.lv.updateLogsRegistration(sender, playerSender, mode);

    return true;
}
`

**Comment by rovertdude** [comment]
Still, we could create a logviewer tool.
Removing /logs won't be too much advised as we have no clue if it can add any errors or crash the server due to /logs not being present.
We should leave /logs.

**Comment by rovertdude** [comment]
I'm locking this for now due to the above.
