### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by xOverloaded** [PugFreedom/WolfFreedom-Core#12]
I need permissions to edit the code without having to request a change on the TV page. I will edit only the messages of commands

**Comment by rovertdude** [comment]
You should have access to do it if you can add labels.

**Comment by xOverloaded** [comment]
mk

**Comment by rovertdude** [comment]
@xOverloaded alright - is that all?

**Comment by xOverloaded** [comment]
Yes, it is

**Comment by rovertdude** [comment]
Alright - resolved and closed.
