### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by rovertdude** [PugFreedom/WolfFreedom-Core#22]
So this is more of a chat thing where you can talk about developer sort of things.

**Comment by adroition** [comment]
You would create this.

**Comment by adroition** [comment]
@xOverloaded well if I was recommended by dev I meet every one of the requirements - recommendations, I've been recommended by the entire Pug Freedom team now.

**Comment by rovertdude** [comment]
@adroition be a dev then! join the WFC!

**Comment by adroition** [comment]
i'll think about rejoining pugfreedom.

**Comment by adroition** [comment]
@rovertdude 
PuggyCrew invited you to join the PugFreedom organization on Feb 5. 
haaa
it's been that long?

**Comment by rovertdude** [comment]
gg

**Comment by xOverloaded** [comment]
Gg

**Comment by adroition** [comment]
4 people in the PugFreedom organization  


@adroition 


adroition
 
 
boom.

**Comment by adroition** [comment]
I'm back!

**Comment by rovertdude** [comment]
gggggg
welcome back adro
