### ISSUE TITLE
ProjectXReloaded

### ISSUE THREAD

**Issue by mr-lukas** [PugFreedom/WolfFreedom-Core#30]
This is now a server, I need a complied TFM, anyone able to do it? @rovertdude, you have joined the github. Ip is projectxrel.g-s.nu

**Comment by rovertdude** [comment]
The compiled version can be found at github.com/TotalFreedom/TotalFreedomMod/releases
However, that is not the WFC.

**Comment by xOverloaded** [comment]
I understand. I was wondering if someone could put it on out github page
