### ISSUE TITLE
/deafen

### ISSUE THREAD

**Issue by adroition** [PugFreedom/WolfFreedom-Core#9]
I'd like to suggest we mostly remove /deafen - it has absolutely no use and can actually be annoying at times.

**Comment by rovertdude** [comment]
/deafen, as long as many other commands. also may be unneeded.
What would this help with?
/deafen is rarely used

**Comment by rovertdude** [comment]
^ this isn't a PR.

**Comment by FriedChckn** [comment]
What technically is it then?

**Comment by rovertdude** [comment]
It's an issue currently - PR is for Pull Request.

**Comment by rovertdude** [comment]
@PuggyCrew 
This is mostly the sort of thing you specialize in - if you can, please review this.
I can see you are currently online.

**Comment by FriedChckn** [comment]
I can edit it, I can remove some commands if you need

**Comment by PuggyCrew** [comment]
agreed with adro.

**Comment by FriedChckn** [comment]
Who is @PuggyCrew ?

**Comment by rovertdude** [comment]
@PuggyCrew is one of the lead developers of the old Pug Freedom Mod - he has access to the PugFreedom additions, I invited him to help us and he approved.
@FriedChckn
